# Generated by Django 4.1.3 on 2022-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slackUsername", models.CharField(max_length=20, unique=True)),
                ("result", models.IntegerField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("AD", "Addition"),
                            ("SB", "Subtraction"),
                            ("MP", "Multiplication"),
                        ],
                        max_length=255,
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
    ]
