# Generated by Django 4.1.3 on 2022-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_operation_slackusername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("ADDITION", "Addition"),
                    ("SUBTRACTION", "Subtraction"),
                    ("MULTIPLICATION", "Multiplication"),
                ],
                max_length=255,
            ),
        ),
    ]
