# Generated by Django 4.1.3 on 2022-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_operation_operation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(max_length=255),
        ),
    ]
